### ISSUE TITLE
API has been retired

### ISSUE THREAD

**Issue by gw0** [smidm/mendeley-add-citations#3]
It seems that Mendeley has retired the API used by `mendeley-oapi-example` library. Now in crashes with:

```
Traceback (most recent call last):
  File "./mendeley_add_citations.py", line 150, in <module>
    documents = mendeley.library(page=0, items=items_per_request)
  File "./mendeley-oapi-example/mendeley_client.py", line 192, in __call__
    content_type = response.headers["Content-Type"]
  File "/home/gw/Projects/StudentPhD/mendeley-add-citations/venv/local/lib/python2.7/site-packages/requests/structures.py", line 77, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'
```

Because the `response` object looks like:

```
>>> print response.header
CaseInsensitiveDict({'date': 'Wed, 18 Feb 2015 15:42:24 GMT', 'transfer-encoding': 'chunked', 'connection': 'keep-alive'})
>>> print response.content
{"message":"This API has been retired. Please see http://dev.mendeley.com for more information."}
```

**Comment by smidm** [comment]
I'm aware of that but currently I don't have a time to fix that. It should be quite easy to base the rewrite on https://github.com/Mendeley/mendeley-api-python-example.

**Comment by smidm** [comment]
fixed
